### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by voiaya** [iiop123/workers-image-hosting#1]
WSL2 Ubuntu@latest
 
![image](https://user-images.githubusercontent.com/18442169/201472894-23271a12-ddfb-4411-9bb3-d2975b7290c3.png)

**Comment by iiop123** [comment]
复制一下static目录新的package.json试试

**Comment by iiop123** [comment]
1.

**Comment by voiaya** [comment]
问题依然存在，已经替换了最新的版本

**Comment by iiop123** [comment]
试试输入npm run build编译。我测试的一切正常
